name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    strategy:
      matrix:
        go-version: ["1.21", "1.23"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: go mod download
      - run: SQLX_MYSQL_DSN=skip SQLX_POSTGRES_DSN=skip SQLX_SQLSERVER_DSN=skip go test -v -count=1 ./...
      - run: go test -v -race -count=1 ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - run: go mod download
      - name: Install tooling
        run: make tooling
      - run: make lint
      - run: make vuln-check

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - run: go mod download
      - name: Install tooling
        run: make tooling
      - run: make fmt
      - run: make has-changes
